output_dir: ~/scratch/protein_output

dataset:
  class: EnzymeCommission
  path: ~/scratch/protein-datasets/
  test_cutoff: 0.95
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: residue
      - class: TruncateProtein
        max_length: 550

task:
  class: MultipleBinaryClassification
  model:
    class: ESM
    path: ~/scratch/protein-model-weights/esm-model-weights/
    model: ESM-1b
  criterion: bce
  metric: ['auprc@micro', 'f1_max']
  num_mlp_layer: 2

optimizer:
  class: Adam
  lr: 1.0e-4

engine:
  gpus: {{ gpus }}
  batch_size: 2
  log_interval: 1000

lr_ratio: 0.1

metric: f1_max

train:
  num_epoch: 200
