output_dir: ~/scratch/protein_output

dataset:
  class: EnzymeCommission
  path: ~/scratch/protein-datasets/
  test_cutoff: 0.95
  transform:
    class: ProteinView
    view: residue

task:
  class: MultipleBinaryClassification
  model:
    class: ProteinResNet
    input_dim: 21
    hidden_dims: [512, 512, 512, 512, 512, 512, 512, 512]
    layer_norm: True
    dropout: 0.1
  criterion: bce
  metric: ['auprc@micro', 'f1_max']
  num_mlp_layer: 2

optimizer:
  class: Adam
  lr: 2.0e-4

engine:
  gpus: {{ gpus }}
  batch_size: 8
  log_interval: 1000

metric: f1_max

train:
  num_epoch: 200
