output_dir: ~/scratch/protein_output

dataset:
  class: GeneOntology
  path: ~/scratch/protein-datasets/
  branch: CC
  test_cutoff: 0.95
  transform:
    class: ProteinView
    view: residue

task:
  class: MultipleBinaryClassification
  model:
    class: ProteinConvolutionalNetwork
    input_dim: 21
    hidden_dims: [1024, 1024]
    kernel_size: 5
    padding: 2
  criterion: bce
  metric: ['auprc@micro', 'f1_max']
  num_mlp_layer: 2

optimizer:
  class: Adam
  lr: 1.0e-4

engine:
  gpus: {{ gpus }}
  batch_size: 32
  log_interval: 1000

metric: f1_max

train:
  num_epoch: 200
